{"timestamp":"2025-08-18T08:40:37.213908","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-18T08:40:37.214397","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_test.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-18T08:40:37.246155Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.246354Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.246423Z","level":"info","event":"Current task name:create_dim_entreprise_table","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.246498Z","level":"info","event":"Dag name:etl_dim_entreprise_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.247607Z","level":"info","event":"Creating table if not exists...","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.248735","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-18T08:40:37.252800","level":"info","event":"Connection Retrieved 'bdd_neon_recette'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-18T08:40:37.254496Z","level":"info","event":"Error creating table: connection to server at \"localhost\" (::1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.254594Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.254660Z","level":"info","event":"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.254717Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.254779Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.254541","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/etl_test.py","lineno":36,"name":"create_table_if_not_exists"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":763,"name":"run"},{"filename":"/usr/local/lib/python3.12/contextlib.py","lineno":137,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":870,"name":"_create_autocommit_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":183,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-18T08:40:37.264432Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.264555Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.264626Z","level":"info","event":"Task:<Task(PythonOperator): create_dim_entreprise_table>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.264686Z","level":"info","event":"Failure caused by connection to server at \"localhost\" (::1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.264778Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.264878Z","level":"info","event":"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.264976Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-18T08:40:37.265082Z","level":"info","event":"","chan":"stdout","logger":"task"}
